In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Melanona_MIBI_TOF_18_7_2024.csv")

In [3]:
df.head()

,Unnamed: 0,Group,pred,patient number,meta_pred,centroid-0,centroid-1,cell_id,fov
0,0,NP,Unidentified,3,Unidentified,3.343373,333.198795,5,FOV10
1,1,NP,Memory%CD4 T cell,3,CD4 T cell,2.814159,1764.212389,11,FOV10
2,2,NP,Hevs,3,Vessels,3.445860,356.878981,15,FOV10
3,3,NP,CD8 T cell,3,CD8 T cell,3.671756,1738.076336,26,FOV10
4,4,NP,Memory%CD4 T cell,3,CD4 T cell,3.485714,1789.857143,27,FOV10

In [4]:
len(df['pred'].unique())

26

In [5]:
wanted_cols = ['pred', 'meta_pred']

df[wanted_cols].drop_duplicates()

                             pred     meta_pred
0                    Unidentified  Unidentified
1               Memory%CD4 T cell    CD4 T cell
2                            Hevs       Vessels
3                      CD8 T cell    CD8 T cell
5                      CD4 T cell    CD4 T cell
18                   CD45RA+MHC2+        Immune
24                        NK cell        Immune
33                            Mac           Mac
34                  blood vessels       Vessels
37                            SMA        Stroma
57                        CD4 APC        Immune
98                         B cell         Bcell
159                           DCs           DCs
165                  Collagen_sma        Stroma
222                  Mono_CD14_DR           Mac
260                      Collagen        Stroma
266                    Neutrophil        Immune
772           CD4 Treg%CD4 T cell    CD4 T cell
897                   DC sign Mac           Mac
1697                    CD206_Mac           Mac
2338   Follicular_Germinal_B_Cell         Bcell
2364               Tfh%CD4 T cell    CD4 T cell
2369               CD14_CD11c_DCs           DCs
3195                     CD68_Mac           Mac
14618       CD11_CD11c_DCsign_DCs           DCs
23661                       tumor         Tumor

In [6]:
translator = {}
for cell_type in df['pred'].unique():
    
    cell_type = cell_type.strip().lower()

    if 'mac' in cell_type or 'mono_cd14_dr' == cell_type:
        translator[cell_type] = 'mac'
        
    elif 'collagen' in cell_type or 'sma' in cell_type:
        translator[cell_type] = 'stroma'
    
    elif 'cd45ra+mhc2+' in cell_type:
        translator[cell_type] = 'b cell'
    
    elif cell_type in ['cd14_cd11c_dcs','cd11_cd11c_dcsign_dcs']:
        translator[cell_type] = 'DC'
        
    elif cell_type == 'tfh%cd4 t cell' or cell_type == 'cd4 apc':
        translator[cell_type] = 'cd4 t cell'


    elif cell_type == 'cd4 treg%cd4 t cell':
        translator[cell_type] = 'Treg'
    
    elif cell_type == 'follicular_germinal_b_cell':
        translator[cell_type] = 'gc'
        
    else:
        translator[cell_type] = cell_type
        
translator

{'unidentified': 'unidentified',
 'memory%cd4 t cell': 'memory%cd4 t cell',
 'hevs': 'hevs',
 'cd8 t cell': 'cd8 t cell',
 'cd4 t cell': 'cd4 t cell',
 'cd45ra+mhc2+': 'b cell',
 'nk cell': 'nk cell',
 'mac': 'mac',
 'blood vessels': 'blood vessels',
 'sma': 'stroma',
 'cd4 apc': 'cd4 t cell',
 'b cell': 'b cell',
 'dcs': 'dcs',
 'collagen_sma': 'stroma',
 'mono_cd14_dr': 'mac',
 'collagen': 'stroma',
 'neutrophil': 'neutrophil',
 'cd4 treg%cd4 t cell': 'Treg',
 'dc sign mac': 'mac',
 'cd206_mac': 'mac',
 'follicular_germinal_b_cell': 'gc',
 'tfh%cd4 t cell': 'cd4 t cell',
 'cd14_cd11c_dcs': 'DC',
 'cd68_mac': 'mac',
 'cd11_cd11c_dcsign_dcs': 'DC',
 'tumor': 'tumor'}

In [7]:
df['pred_mapped'] = df['pred'].apply(lambda x: translator[x.strip().lower()])
df

,Unnamed: 0,Group,pred,patient number,meta_pred,centroid-0,centroid-1,cell_id,fov,pred_mapped
0,0,NP,Unidentified,3,Unidentified,3.343373,333.198795,5,FOV10,unidentified
1,1,NP,Memory%CD4 T cell,3,CD4 T cell,2.814159,1764.212389,11,FOV10,memory%cd4 t cell
2,2,NP,Hevs,3,Vessels,3.445860,356.878981,15,FOV10,hevs
3,3,NP,CD8 T cell,3,CD8 T cell,3.671756,1738.076336,26,FOV10,cd8 t cell
4,4,NP,Memory%CD4 T cell,3,CD4 T cell,3.485714,1789.857143,27,FOV10,memory%cd4 t cell
...,...,...,...,...,...,...,...,...,...,...
1652269,1701053,PP,Follicular_Germinal_B_Cell,104,Bcell,2022.567308,1446.775641,12395,FOV98,gc
1652270,1701054,PP,CD4 T cell,104,CD4 T cell,2024.406977,405.038760,12401,FOV98,cd4 t cell
1652271,1701055,PP,CD4 T cell,104,CD4 T cell,2028.045000,496.570000,12437,FOV98,cd4 t cell
1652272,1701056,PP,B cell,104,Bcell,2032.712766,1208.500000,12457,FOV98,b cell
1652273,1701057,PP,B cell,104,Bcell,2038.929630,1218.292593,12504,FOV98,b cell

df.to_csv('mapped_cell_types.csv', index=False)

In [8]:
df.to_csv('mapped_cell_types.csv', index=False)